[build-system]
name = "ebook2audiobook"
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "ebook2audiobook"
version = "25.10.30"

[tool.setuptools.dynamic]
version = {file = "VERSION.txt"}

[project]
name = "ebook2audiobook"
description = "Convert eBooks to audiobooks with chapters and metadata"
authors = [
    { name = "Drew Thomasson" }
]
dependencies = [
    "absl-py==2.3.1",
    "aiofiles==24.1.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.13.1",
    "aiosignal==1.4.0",
    "alabaster==1.0.0",
    "alembic==1.17.0",
    "annotated-doc==0.0.3",
    "annotated-types==0.7.0",
    "antlr4-python3-runtime==4.9.3",
    "anyascii==0.3.3",
    "anyio==4.11.0",
    "argostranslate==1.10.0",
    "asteroid-filterbanks==0.4.0",
    "attrs==25.4.0",
    "audioread==3.0.1",
    "babel==2.17.0",
    "bangla==0.0.5",
    "beautifulsoup4==4.14.2",
    "blis==0.7.11",
    "bnnumerizer==0.0.2",
    "bnunicodenormalizer==0.1.7",
    "Brotli==1.1.0",
    "catalogue==2.0.10",
    "certifi==2025.10.5",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "click==8.2.1",
    "cloudpathlib==0.23.0",
    "cloudpickle==3.1.1",
    "colorama==0.4.6",
    "colorlog==6.10.1",
    "confection==0.1.5",
    "contourpy==1.3.3",
    "coqpit-config==0.2.1",
    "coqui-tts==0.27.2",
    "coqui-tts-trainer==0.3.1",
    "csvw==3.7.0",
    "ctranslate2==4.6.0",
    "cutlet==0.5.0",
    "cycler==0.12.1",
    "cymem==2.0.11",
    "Cython==3.1.6",
    "dateparser==1.1.8",
    "decorator==5.2.1",
    "deep-translator==1.11.4",
    "demucs==4.0.1",
    "dlinfo==2.0.0",
    "docker==7.1.0",
    "docopt==0.6.2",
    "docutils==0.21.2",
    "dora_search==0.1.12",
    "EbookLib==0.19",
    "einops==0.8.1",
    "emoji==2.15.0",
    "encodec==0.1.1",
    "fastapi==0.120.0",
    "ffmpy==0.6.4",
    "filelock==3.20.0",
    "fonttools==4.60.1",
    "frozenlist==1.8.0",
    "fsspec==2025.9.0",
    "fugashi==1.5.2",
    "g2pkk==0.1.2",
    "gradio==5.49.1",
    "gradio_client==1.13.3",
    "greenlet==3.2.4",
    "groovy==0.1.2",
    "grpcio==1.76.0",
    "gruut==2.4.0",
    "gruut-ipa==0.13.0",
    "gruut_lang_de==2.0.1",
    "gruut_lang_en==2.0.1",
    "gruut_lang_es==2.0.1",
    "gruut_lang_fr==2.0.2",
    "h11==0.16.0",
    "hangul-romanize==0.1.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "huggingface-hub==0.36.0",
    "HyperPyYAML==1.2.2",
    "idna==3.11",
    "imagesize==1.4.1",
    "indic-nlp-library==0.92",
    "inflect==7.5.0",
    "iso639-lang==2.6.3",
    "isodate==0.7.2",
    "jaconv==0.4.0",
    "jamo==0.4.1",
    "jieba==0.42.1",
    "Jinja2==3.1.6",
    "joblib==1.5.2",
    "jsonlines==1.2.0",
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.9.1",
    "julius==0.2.7",
    "kiwisolver==1.4.9",
    "lameenc==1.8.1",
    "langcodes==3.5.0",
    "language-tags==1.2.0",
    "language_data==1.3.0",
    "lazy_loader==0.4",
    "libretranslatepy==2.1.1",
    "librosa==0.11.0",
    "lightning==2.5.5",
    "lightning-utilities==0.15.2",
    "llvmlite==0.45.1",
    "lxml==6.0.2",
    "Mako==1.3.10",
    "marisa-trie==1.3.1",
    "Markdown==3.9",
    "markdown-it-py==4.0.0",
    "MarkupSafe==3.0.3",
    "matplotlib==3.10.7",
    "mdurl==0.1.2",
    "mecab-python3==1.0.10",
    "mojimoji==0.0.13",
    "monotonic-alignment-search==0.2.1",
    "more-itertools==10.8.0",
    "Morfessor==2.0.6",
    "mpmath==1.3.0",
    "msgpack==1.1.2",
    "multidict==6.7.0",
    "murmurhash==1.0.13",
    "mutagen==1.47.0",
    "networkx==3.5",
    "nltk==3.9.2",
    "num2words @ git+https://github.com/savoirfairelinux/num2words.git@07814cb114157f582c40a00119c2e9faba8dcee2",
    "numba==0.62.1",
    "numpy==1.26.4",
    "nvidia-ml-py==13.580.82",
    "omegaconf==2.3.0",
    "openunmix==1.3.0",
    "optuna==4.5.0",
    "orjson==3.11.4",
    "packaging==25.0",
    "pandas==2.3.3",
    "phonemizer-fork==3.3.2",
    "pillow==11.3.0",
    "plac==1.4.5",
    "platformdirs==4.5.0",
    "pooch==1.8.2",
    "preshed==3.0.10",
    "primePy==1.3",
    "propcache==0.4.1",
    "protobuf==6.33.0",
    "psutil==7.1.2",
    "pyannote.audio==3.4.0",
    "pyannote.core==5.0.0",
    "pyannote.database==5.1.3",
    "pyannote.metrics==3.2.1",
    "pyannote.pipeline==3.0.1",
    "pycantonese==3.4.0",
    "pycparser==2.23",
    "pydantic==2.11.10",
    "pydantic_core==2.33.2",
    "pydub==0.25.1",
    "Pygments==2.19.2",
    "pylangacq==0.16.2",
    "PyMuPDF==1.26.5",
    "pymupdf4llm==0.0.27",
    "PyOpenGL==3.1.10",
    "pyparsing==3.2.5",
    "pypinyin==0.55.0",
    "pysbd==0.3.4",
    "pythainlp==5.1.2",
    "python-crfsuite==0.9.11",
    "python-dateutil==2.9.0.post0",
    "python-multipart==0.0.20",
    "pytorch-lightning==2.5.5",
    "pytorch-metric-learning==2.9.0",
    "pytz==2025.2",
    "pywin32; sys_platform == 'win32'",
    "PyYAML==6.0.3",
    "ray==2.50.1",
    "rdflib==7.3.0",
    "referencing==0.37.0",
    "regex==2025.10.23",
    "requests==2.32.5",
    "resampy==0.4.3",
    "retrying==1.4.2",
    "rfc3986==1.5.0",
    "rich==14.2.0",
    "roman-numerals-py==3.1.0",
    "rpds-py==0.28.0",
    "ruamel.yaml==0.18.16",
    "ruamel.yaml.clib==0.2.14",
    "ruff==0.14.2",
    "sacremoses==0.1.1",
    "safehttpx==0.1.7",
    "safetensors==0.6.2",
    "scikit-learn==1.7.2",
    "scipy==1.16.2",
    "segments==2.3.0",
    "semantic-version==2.10.0",
    "semver==3.0.4",
    "sentencepiece==0.2.1",
    "setuptools==80.9.0",
    "shellingham==1.5.4",
    "six==1.17.0",
    "smart_open==7.4.1",
    "sniffio==1.3.1",
    "snowballstemmer==3.0.1",
    "sortedcontainers==2.4.0",
    "soundfile==0.13.1",
    "soupsieve==2.8",
    "soxr==1.0.0",
    "soynlp==0.0.493",
    "spacy==3.7.5",
    "spacy-legacy==3.0.12",
    "spacy-loggers==1.0.5",
    "speechbrain==1.0.3",
    "Sphinx==8.2.3",
    "sphinx-argparse==0.5.2",
    "sphinx-rtd-theme==3.0.2",
    "sphinxcontrib-applehelp==2.0.0",
    "sphinxcontrib-devhelp==2.0.0",
    "sphinxcontrib-htmlhelp==2.1.0",
    "sphinxcontrib-jquery==4.1",
    "sphinxcontrib-jsmath==1.0.1",
    "sphinxcontrib-qthelp==2.0.0",
    "sphinxcontrib-serializinghtml==2.0.0",
    "SQLAlchemy==2.0.44",
    "srsly==2.5.1",
    "stanza==1.10.1",
    "starlette==0.48.0",
    "submitit==1.5.3",
    "SudachiDict-core==20250825",
    "SudachiPy==0.6.10",
    "sympy==1.14.0",
    "tabulate==0.9.0",
    "tensorboard==2.20.0",
    "tensorboard-data-server==0.7.2",
    "tensorboardX==2.6.4",
    "termcolor==3.1.0",
    "thinc==8.2.5",
    "threadpoolctl==3.6.0",
    "tokenizers==0.21.4",
    "tomlkit==0.13.3",
    "torch==2.7.1",
    "torch-audiomentations==0.12.0",
    "torch_pitch_shift==1.2.5",
    "torchaudio==2.7.1",
    "torchmetrics==1.8.2",
    "torchvggish==0.2",
    "tqdm==4.67.1",
    "transformers==4.55.4",
    "translate==3.6.1",
    "treetable==0.2.6",
    "typeguard==4.4.4",
    "typer==0.20.0",
    "typing-inspection==0.4.2",
    "typing_extensions==4.15.0",
    "tzdata==2025.2",
    "tzlocal==5.3.1",
    "unidic==1.1.0",
    "unidic-lite==1.0.8",
    "uritemplate==4.2.0",
    "urllib3==2.5.0",
    "uvicorn==0.38.0",
    "wasabi==0.10.1",
    "wcwidth==0.2.14",
    "weasel==0.4.1",
    "websockets==15.0.1",
    "Werkzeug==3.1.3",
    "wheel==0.45.1",
    "wordseg==0.0.2",
    "wrapt==2.0.0",
    "yarl==1.22.0",
]
readme = "README.md"
requires-python = ">3.9,<3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
scripts = { "ebook2audiobook" = "app:main" }

[project.urls]
"Homepage" = "https://github.com/DrewThomasson/ebook2audiobook"
absl-py==2.3.1
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.13.1
aiosignal==1.4.0
alabaster==1.0.0
alembic==1.17.0
annotated-doc==0.0.3
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyascii==0.3.3
anyio==4.11.0
argostranslate==1.10.0
asteroid-filterbanks==0.4.0
attrs==25.4.0
audioread==3.0.1
babel==2.17.0
bangla==0.0.5
beautifulsoup4==4.14.2
blis==0.7.11
bnnumerizer==0.0.2
bnunicodenormalizer==0.1.7
brotli==1.1.0
catalogue==2.0.10
certifi==2025.10.5
cffi==2.0.0
charset-normalizer==3.4.4
click==8.2.1
cloudpathlib==0.23.0
cloudpickle==3.1.1
colorama==0.4.6
colorlog==6.10.1
confection==0.1.5
contourpy==1.3.3
coqpit-config==0.2.1
coqui-tts==0.27.2
coqui-tts-trainer==0.3.1
csvw==3.7.0
ctranslate2==4.6.0
cutlet==0.5.0
cycler==0.12.1
cymem==2.0.11
cython==3.1.6
dateparser==1.1.8
decorator==5.2.1
deep-translator==1.11.4
demucs==4.0.1
dlinfo==2.0.0
docker==7.1.0
docopt==0.6.2
docutils==0.21.2
dora-search==0.1.12
ebooklib==0.19
einops==0.8.1
emoji==2.15.0
encodec==0.1.1
fastapi==0.120.0
ffmpy==0.6.4
filelock==3.20.0
fonttools==4.60.1
frozenlist==1.8.0
fsspec==2025.9.0
fugashi==1.5.2
g2pkk==0.1.2
gradio==5.49.1
gradio-client==1.13.3
greenlet==3.2.4
groovy==0.1.2
grpcio==1.76.0
gruut==2.4.0
gruut-ipa==0.13.0
gruut-lang-de==2.0.1
gruut-lang-en==2.0.1
gruut-lang-es==2.0.1
gruut-lang-fr==2.0.2
h11==0.16.0
hangul-romanize==0.1.0
httpcore==1.0.9
httpx==0.28.1
huggingface-hub==0.36.0
hyperpyyaml==1.2.2
idna==3.11
imagesize==1.4.1
indic-nlp-library==0.92
inflect==7.5.0
iso639-lang==2.6.3
isodate==0.7.2
jaconv==0.4.0
jamo==0.4.1
jieba==0.42.1
jinja2==3.1.6
joblib==1.5.2
jsonlines==1.2.0
jsonschema==4.25.1
jsonschema-specifications==2025.9.1
julius==0.2.7
kiwisolver==1.4.9
lameenc==1.8.1
langcodes==3.5.0
language-data==1.3.0
language-tags==1.2.0
lazy-loader==0.4
libretranslatepy==2.1.1
librosa==0.11.0
lightning==2.5.5
lightning-utilities==0.15.2
llvmlite==0.45.1
lxml==6.0.2
mako==1.3.10
marisa-trie==1.3.1
markdown==3.9
markdown-it-py==4.0.0
markupsafe==3.0.3
matplotlib==3.10.7
mdurl==0.1.2
mecab-python3==1.0.10
mojimoji==0.0.13
monotonic-alignment-search==0.2.1
more-itertools==10.8.0
morfessor==2.0.6
mpmath==1.3.0
msgpack==1.1.2
multidict==6.7.0
murmurhash==1.0.13
mutagen==1.47.0
networkx==3.5
nltk==3.9.2
num2words @ git+https://github.com/savoirfairelinux/num2words.git@07814cb114157f582c40a00119c2e9faba8dcee2
numba==0.62.1
numpy==1.26.4
nvidia-ml-py==13.580.82
omegaconf==2.3.0
openunmix==1.3.0
optuna==4.5.0
orjson==3.11.4
packaging==25.0
pandas==2.3.3
phonemizer-fork==3.3.2
pillow==11.3.0
pip==25.3
plac==1.4.5
platformdirs==4.5.0
pooch==1.8.2
preshed==3.0.10
primepy==1.3
propcache==0.4.1
protobuf==6.33.0
psutil==7.1.2
pyannote-audio==3.4.0
pyannote-core==5.0.0
pyannote-database==5.1.3
pyannote-metrics==3.2.1
pyannote-pipeline==3.0.1
pycantonese==3.4.0
pycparser==2.23
pydantic==2.11.10
pydantic-core==2.33.2
pydub==0.25.1
pygments==2.19.2
pylangacq==0.16.2
pymupdf==1.26.5
pymupdf4llm==0.0.27
pyopengl==3.1.10
pyparsing==3.2.5
pypinyin==0.55.0
pysbd==0.3.4
pythainlp==5.1.2
python-crfsuite==0.9.11
python-dateutil==2.9.0.post0
python-multipart==0.0.20
pytorch-lightning==2.5.5
pytorch-metric-learning==2.9.0
pytz==2025.2
pywin32==311
pyyaml==6.0.3
ray==2.50.1
rdflib==7.3.0
referencing==0.37.0
regex==2025.10.23
requests==2.32.5
resampy==0.4.3
retrying==1.4.2
rfc3986==1.5.0
rich==14.2.0
roman-numerals-py==3.1.0
rpds-py==0.28.0
ruamel-yaml==0.18.16
ruamel-yaml-clib==0.2.14
ruff==0.14.2
sacremoses==0.1.1
safehttpx==0.1.7
safetensors==0.6.2
scikit-learn==1.7.2
scipy==1.16.2
segments==2.3.0
semantic-version==2.10.0
semver==3.0.4
sentencepiece==0.2.1
setuptools==80.9.0
shellingham==1.5.4
six==1.17.0
smart-open==7.4.1
sniffio==1.3.1
snowballstemmer==3.0.1
sortedcontainers==2.4.0
soundfile==0.13.1
soupsieve==2.8
soxr==1.0.0
soynlp==0.0.493
spacy==3.7.5
spacy-legacy==3.0.12
spacy-loggers==1.0.5
speechbrain==1.0.3
sphinx==8.2.3
sphinx-argparse==0.5.2
sphinx-rtd-theme==3.0.2
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
sqlalchemy==2.0.44
srsly==2.5.1
stanza==1.10.1
starlette==0.48.0
submitit==1.5.3
sudachidict-core==20250825
sudachipy==0.6.10
sympy==1.14.0
tabulate==0.9.0
tensorboard==2.20.0
tensorboard-data-server==0.7.2
tensorboardx==2.6.4
termcolor==3.1.0
thinc==8.2.5
threadpoolctl==3.6.0
tokenizers==0.21.4
tomlkit==0.13.3
torch==2.7.1
torch-audiomentations==0.12.0
torch-pitch-shift==1.2.5
torchaudio==2.7.1
torchmetrics==1.8.2
torchvggish==0.2
tqdm==4.67.1
transformers==4.55.4
translate==3.6.1
treetable==0.2.6
typeguard==4.4.4
typer==0.20.0
typing-extensions==4.15.0
typing-inspection==0.4.2
tzdata==2025.2
tzlocal==5.3.1
unidic==1.1.0
unidic-lite==1.0.8
uritemplate==4.2.0
urllib3==2.5.0
uv==0.9.5
uvicorn==0.38.0
wasabi==0.10.1
wcwidth==0.2.14
weasel==0.4.1
websockets==15.0.1
werkzeug==3.1.3
wheel==0.45.1
wordseg==0.0.2
wrapt==2.0.0
yarl==1.22.0
