[build-system]
name = "ebook2audiobook"
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "ebook2audiobook"
version = {file = "VERSION.txt"}

[tool.setuptools.dynamic]
version = {file = "VERSION.txt"}

[project]
name = "ebook2audiobook"
description = "Convert eBooks to audiobooks with chapters and metadata"
authors = [
    { name = "Drew Thomasson" }
]
dependencies = [
	"tqdm",
	"torchvggish",
	"regex",
	"docker",
	"ebooklib",
	"fastapi",
	"hf_xet",
	"beautifulsoup4",
	"nagisa",
	"pymupdf",
	"pymupdf-layout",
	"pytesseract",
	"unidic",
	"hangul-romanize",
	"indic-nlp-library",
	"iso639-lang",
	"jieba",
	"pycantonese",
	"soynlp",
	"pypinyin",
	"pythainlp",
	"mutagen",
	"PyOpenGL",
	"phonemizer-fork",
	"pydub",
	"unidecode",
	"langdetect",
	"stanza==1.10.1",
	"pyannote-audio==4.0.3",
	"argostranslate<=1.10.0",
	"gradio==6.5.1",
	"torch==2.7.1",
	"torchaudio==2.7.1",
	"coqui-tts[languages]==0.27.5"
]
readme = "README.md"
requires-python = ">3.9,<3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
scripts = { "ebook2audiobook" = "app:main" }

[project.urls]
"Homepage" = "https://github.com/DrewThomasson/ebook2audiobook"